version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10
    labels:
      - "Type: Dependency Upgrade"
      - "Priority 1: Must"
    milestone: 16
    groups:
      github-dependencies:
        update-types:
          - "patch"
          - "minor"
          - "major"

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 10
    labels:
      - "Type: Dependency Upgrade"
      - "Priority 1: Must"
    milestone: 16
    groups:
      maven-dependencies:
        update-types:
          - "patch"
          - "minor"
          - "major"
    ignore:
      - dependency-name: "org.mockito:*"
        versions: [ "[5.0.0,)" ]
      - dependency-name: "org.springframework.boot:*"
        versions: [ "[3.0.0,)" ]