# We want to run this on Ubuntu 18.04 LTS
dist: bionic

language: java

sudo: required

services:
  - docker

jobs:
  include:
    - name: "JDK 8"
      jdk: openjdk8
      env: MVN_BUILD_SCRIPT="clean verify"
    - name: "JDK 11 with Sonar analysis"
      jdk: openjdk11
      env: MVN_BUILD_SCRIPT="-Pcoverage clean verify sonar:sonar -Dsonar.projectKey=AxonFramework_extension-tracing"

install: true

cache:
  directories:
    - $HOME/.m2

# We switch JDK by setting the JAVA_HOME environment variable. All JDKs are under the same base directory.
script:
  - mvn -version
  - mvn -B -U $MVN_BUILD_SCRIPT

notifications:
  slack:
    secure: d1HN9GBeH0e6EsHjNkPVXgBaFCYqbvjkZv9GUkpWnyjNYP5V1snSk6sO4X6ONttydgzfbElZTOfrgDzRTgWJ76iDMxAPccFPY7dmGcpw8/2TOjwP6H6yEitiiZcWR9fssTM2Li2WQtuGkwaVBhw15JNABzEsexxqXC+Cu48yUfA=

addons:
  sonarcloud:
    organization: "axonframework"
    token:
      secure: "N1EPrmz4TiTNsdnxLMUCHsyuIXa6riRopSX9j6+PnqC/bPDemUTojjTyAo6GOiBNTVLdxT9TZ1tNoKYWPdKM2Vj/7EX/Z8BCms7hWd/TnRPNuWCMl8tAx9LUPrcn/EyqkdPKCsDAFt94U8VMRJiGrqHPIiShY91iAWlCu/Lyh+E0MwU2vjGYtAv0PFsdXdZtlQn8m5ZH8mD206pz+6YvgAu++hgx7S4k/pD1sxYitqLeRLhavvlWhsHpk2cTlgCU13YVWV/EXY14IMgAIrvJ6lO3/N10UQtlJfLmmIqtvxHTTxiAn91s08xeJksTC9C7iB/b15vENh2sP8h7vBA+npF/wzQkjeplccy4pBdBQkHHsNZ5n6zSYsDcmljl5edoP9n1+aScmxeYfF8XJBCWqXL21WtaYpwfVLQf8NMPoLicF5m1wvyVc1c4E9yDVF2Arbr2h9n70PFZ1JxqSBEmW8sSfZcqnrTN3MZKDb3WHy2SfVzlFtujIVlVu280dovOzcgNE6119QaqvR1IWsB+e+FQaZXEPTfWHxZrlROvzm+UqJbNz16v5NKebor9rLtnfPalQ4imqCQdETzjLQRuLuxXDCgrR2vi9IG6Dgv+x0OcUlOsy1z+7unK+CZDj9ZKrHHVhvZduQLwbvukOqkQCFwGifLaH8Zq4hqAQeVQgJI="