:navtitle: Configuring the Extension
= Configuring the Extension

The extension can be disabled setting the property `axon.extension.tracing.enabled` to `false` (default=`true`). This will give you the possibility to turn it off when needed (for example, for a certain environment).

Furthermore, there is a more fine-grained configuration option of the tracing span tags on commands, events and queries. You can customize span tags easily, mixing and matching between available tag `MESSAGE_ID`, `AGGREGATE_ID`, `MESSAGE_TYPE`, `PAYLOAD_TYPE`, `MESSAGE_NAME` and `PAYLOAD`. Take into account that some of the tags make sense on a certain span type, but not on another, and some of them have an hidden cost on network (such as payload). Use them wisely.

[source,properties]
----
axon.extension.tracing.span.commandTags=MESSAGE_ID, MESSAGE_TYPE, PAYLOAD_TYPE, MESSAGE_NAME
axon.extension.tracing.span.eventTags=MESSAGE_ID, AGGREGATE_ID, MESSAGE_TYPE, PAYLOAD_TYPE
axon.extension.tracing.span.queryTags=MESSAGE_ID, MESSAGE_TYPE, PAYLOAD_TYPE, MESSAGE_NAME
----

Above an example of the default value. Available tags field are listed in link:https://github.com/AxonFramework/extension-tracing/blob/master/tracing/src/main/java/org/axonframework/extensions/tracing/MessageTag.java[MessageTag.java,window=_blank,role=external] class.
