version: '3.5'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaegertracing
    ports:
      - 16686:16686
      - "6831:6831/udp"
      - "6832:6832/udp"
    networks:
      - default
